module.exports = {
  content: ["./index.html"],
  theme: {
    extend: {
      backgroundImage: {
        sanFrancisco: "url(`../public/img/sanFrancisco.jpg)",
        sanFranciscoDesktop: "url('../public/img/sanFranciscoDesktop.jpg')",
        yosemite: "url('../public/img/yosemite.jpg')",
        LA: "url('../public/img/LA.jpg')",
        seattle: "url('../public//img/seattle.jpg')",
        new_york: "url('../public/img/new_york.jpg')",
        norway: "url('../public/img/norway.jpg')",
        sydney: "url('../public/img/sydney.jpg')",
        miami: "url('../public/img/miami.jpg')",
        switzerland: "url('../public/img/switzerland.jpg')",
        bali: "url('../public/img/bali.jpg')",
        norway: "url('../public/img/norway.jpg')",
        chicago: "url('../public/img/chicago.jpg')",
        europe: "url('../public/img/europe.jpg')",
        iceland: "url('../public/img/iceland.jpg')",
        img1: "url('../public/img/img1.jpg')",
        img2: "url('../public/img/img2.png')",
        img3: "url('../public/img/img3.png')",
        img4: "url('../public/img/img4.png')",
        img5: "url('../public/img/img5.png)",
        img6: "url('../public/img/img6.jpg')",
        img7: "url('../public/img/img7.jpg')",
        img8: "url('../public/img/img8.jpg')",
        img9: "url('../public/img/img9.jpg')",
        img10: "url('../public/img/img10.jpg')",
      },
      backgroundColor: (theme) => ({
        ...theme("colors"),
        principal: "#CC2D4A",
        secondary: "#8FA206",
        tertiary: "#61AEC9",
      }),
      textColor: {
        principal: "#CC2D4A",
        secondary: "#8FA206",
        tertiary: "#61AEC9",
      },
      fontFamily: {
        Montserrat: ["Montserrat", "sans-serif"],
      },
    },
  },
  plugins: [],
};
